server:
  port: 1010

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: MUSIC-SERVICE
          uri: lb://MUSIC-SERVICE
          predicates:
            - Path=/music/api/v1/**




eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
